### PR TITLE
Load language via user setup

### PR DESCRIPTION
**Pull request by iMattPro**

### CODE REVIEW

**Review by rxu — COMMENTED** [review]
While the code looks good, but tbh I don't like the idea of loading [language] files globally without actual necessity. But this way is the simpliest either 😃

**Review by senky — COMMENTED** [review]
If I understand it correctly, the lang file is used on index and viewforum pages only, right? Can't you use a condition in `load_language_on_setup` to load extra file only in such cases?

**Comment by rxu** [comment]
That would mean to have these checks on thousands of unrelated pages for the sake of loading on several of them only. Looks suboptimal.

**Comment by iMattPro** [comment]
It’s only got 1 lang var so I don’t see any problem. 

Also because this ext is extendable it’s possible someone may need it on more than just the index page. 

This change was suggested by the validators.

**Review by senky — APPROVED** [review]

**Review by kasimi — APPROVED** [review]

**Pull request merged**
