### PR TITLE
Adding edits for Hexagon style

### PR DESCRIPTION
**Pull request by MannixMD**
Hi if you could review and add the adjustments i made for my Hexagon style.

### CODE REVIEW

**Comment by iMattPro** [comment]
You should look at our other 3rd party styles. You need to import our base CSS and then just do the over-rides you need.

**Comment by MannixMD** [comment]
Isn't that what i did ? I just added an image to better fit my style rather then just make it ugly square and made the edits in collapsiblecategories.css

**Comment by DavidIQ** [comment]
Not really. You basically copied the whole base file. You should be doing something more like this:
https://github.com/phpbb-extensions/collapsible-categories/blob/master/styles/Green-Style/theme/collapsiblecategories.css
Only overriding the classes you need to change for your style.

**Comment by iMattPro** [comment]
Also we do not use images. You can easily achieve the same effect with some simple CSS changes.

**Comment by MannixMD** [comment]
Ok thanks for the help. Will be back with fix soon :)

**Comment by iMattPro** [comment]
You're still not importing the base style and only using the CSS you need to change like the other styles, and the image still needs to be removed.

**Comment by iMattPro** [comment]
Dealt with here #63

**Pull request closed without merging**
