### PR TITLE
Clean up javascript, Security Enahncements

### PR DESCRIPTION
**Pull request by iMattPro**

### CODE REVIEW

**Comment by Wolfsblvt** [comment]
I have learned that spaces before brackets on if and function defines are good for better readability :D

Changes look okay, so can be merged.

**Comment by iMattPro** [comment]
It's totally subjective, but here we should do as the coding practices throughout the rest of phpBB does, since this is an official phpBB extension, and they do not use the extra spaces (also saves extra bytes) ;)

**Comment by Wolfsblvt** [comment]
If you talk about bytes, you should consider minifying it, so bad argument :P
Coding guidelines are okay for me, didn't know that this was the case here.
I think my IDE uses spaces when I autoformat a js document.

**Comment by iMattPro** [comment]
@Wolfsblvt if we were minifying this, then yeah it'd be a bad argument, but since we are not minifying it, anywhere we can shave a waste of bytes is actually a good thing :smile:

**Comment by iMattPro** [comment]
Updated this PR with a security enhancement. Even though symfony routing should prevent possible injection attacks due to our slug requirement, added an extra check to make extra sure we only receive valid data.

**Comment by Wolfsblvt** [comment]
Great idea, can't hurt to do that.

**Comment by rxu** [comment]
Is there an actual scenario for phpBB where `forum_id` can be not digit-only?

**Comment by iMattPro** [comment]
@rxu remember we are actually changing the forum id into fid_1, fid_2, etc, because we wanted to leave open the possibility for this to be applicable to other extensions with non-forums that are wrapped in the similar structure/layout of an elem with the class forabg...for example: shoutbox or mchat, recent topics, etc. So they would be able to identify themselves uniquely like with shoutbox_1, rt_1, rt_2 or whatever.

**Comment by rxu** [comment]
Ah, ok. It's just `forum_id` param name which makes me feel it should be `\d+` :)
The patch looks good then.

**Comment by Wolfsblvt** [comment]
I think "identifier" doesn't generally mean it is an `int`. It is just widely used in this case, so people get familiar with it.
Identifier is just something for identifying elements :P

**Pull request merged**
